"""add email fields to task

Revision ID: 9c848b3196f5
Revises: 8db6a9f6882b
Create Date: 2026-06-24 09:29:46.998451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c848b3196f5'
down_revision: Union[str, Sequence[str], None] = '8db6a9f6882b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('email_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('task', sa.Column('email_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('task', sa.Column('email_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'email_body')
    op.drop_column('task', 'email_subject')
    op.drop_column('task', 'email_to')
    # ### end Alembic commands ###
