"""add cascade delete to taskrun

Revision ID: f266e7cc84e1
Revises: 91b97ac519bf
Create Date: 2026-06-18 14:51:44.835705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f266e7cc84e1'
down_revision: Union[str, Sequence[str], None] = '91b97ac519bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taskrun', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('taskrun_task_id_fkey'), 'taskrun', type_='foreignkey')
    op.create_foreign_key(None, 'taskrun', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taskrun', type_='foreignkey')
    op.create_foreign_key(op.f('taskrun_task_id_fkey'), 'taskrun', 'task', ['task_id'], ['id'])
    op.alter_column('taskrun', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
